version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "usama-fargate"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pbiibbw6jz4a"
s3_prefix = "usama-fargate"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
